# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

[package]
title = "Hunyuan3D-2 Support"
version = "0.1.0"  # Semantic Versionning is used: https://semver.org/
description = "The simplest python extension example. Use it as a starting point for your extensions."
category = "Example"  # How to categorize this in the Extension Manager
changelog = "docs/CHANGELOG.md"
icon = "data/icon.png"  # Icon to show in the Extension Manager
keywords = ["kit", "example", "extension"]  # Search keywords for the Extension Manager
preview_image = "data/preview.png"  # Preview to show in the Extension Manager
readme  = "docs/README.md"  # Path (relative to the root) or content of readme markdown file for UI
repository = "https://github.com/NVIDIA-Omniverse/kit-app-template"  # URL of the extension source repository


[dependencies]
"omni.kit.pip_archive" = {}
"genai.packages.core" = {}

[settings]


[[python.module]]  # Main python module this extension provides, it will be publicly available as "import genai.hunyuan3d.core"
name = "genai.hunyuan3d.core"


[documentation]
pages = [
    "docs/Overview.md",
    "docs/CHANGELOG.md",
]

[python.pipapi]
requirements = [
    'gitpython',
    'pyyaml',
    'numpy',
    'pillow',
    'imageio',
    'onnxruntime',
    'rembg',
    'trimesh',

    'diffusers',
    'transformers',
    'einops',
    'pymeshlab==2023.12.post1',  #need this, otherwise it wil crash on import on windows
    'accelerate',
    'sentencepiece',
    'xatlas',
    'huggingface_hub',
    'pygltflib',

]
extra_args = ["--extra-index-url", "https://download.pytorch.org/whl/cu124"]

use_online_index = true


[[test]]
dependencies = [

]
# 5 hours timeout, may take very long time to download the model
timeout = 18000

args = [
]